### ISSUE TITLE
Beaudry_Issue_For_Blubaugh

### ISSUE THREAD

**Issue by MeganSarah** [epid8060fall2019/AMANDA_BLUBAUGH-introduction#1]
Hi Amanda!
I really enjoyed your website, it was very personable and informative. I could sense your love of animals. For my "issue", I would like to know that if you could have any animal in the world what would it be? 

On a more personal note, for another question, I would like to know how you deal with balancing obtaining your DVM and PhD at the same time? 

Have a great day,
Megan

**Comment by alblubaugh** [comment]
Hi Megan,

I love the issue you gave me; it is a true dilemma.  :) 
I think I would have a pet fox if it were possible. I have always loved foxes: they are so playful and behaviorally seem like an awesome mix of cats and dogs.

As far as balancing obtaining the two degrees, I am lucky the program is extremely well structured.  While I am working on the PhD, I am not in vet med classes simultaneously.  So far, I have completed the first two years of vet med, and now I am on the second year of the PhD. Once I finish the PhD, I will return to the last two years of the vet med program.  I do think the best way to balance everything is through taking baby steps each day and not getting boggled down in the idea of the enormity of work that is left. 

Good to meet you!

Amanda
